services:
  - type: web
    name: fan-proposals-backend
    env: node
    plan: free
    branch: main
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        fromDatabase:
          name: fan-proposals-config
          property: supabase_url
      - key: SUPABASE_SERVICE_KEY
        fromDatabase:
          name: fan-proposals-config
          property: supabase_service_key